### ISSUE TITLE
How i can update getUpdates offset?

### ISSUE THREAD

**Issue by weiddolo** [yukuku/telebot#26]
The bot crashes when I reach the limit in getUpdates. How i can update offset in each message received?

**Comment by coriumalpha** [comment]
I think that there is an error in `/updates` method.
Telegram Bot API's is not supporting any call to `/getUpdates` while a webhook is set.

Then, Telebot cannot parse the result 'cause it doesn't exist.

Calling `updates` implies calling `BASE_URL + 'getUpdates'`, if getUpdates is dissabled you will get an error caused by the following line:
`self.response.write(json.dumps(json.load(urllib2.urlopen(BASE_URL + 'getUpdates'))))`
